### ISSUE TITLE
Weird random scrollbars

### ISSUE THREAD

**Issue by kccuber-scratch** [Oren-Lindsey/scratch-cloud#1]
Not sure what's happening but for me there's a random horizontal scrollbar which makes it show this thing on the side (I'm talking about that white line):
![image](https://user-images.githubusercontent.com/92891642/177593550-df36cc50-0357-4ba6-942b-44643b2db300.png)
And there's also a vertical scroll on the homepage for some reason:
![image](https://user-images.githubusercontent.com/92891642/177593791-689acc3e-9d2b-465e-b70a-610b64024a69.png)

**Comment by Oren-Lindsey** [comment]
The vertical scrollbar is because the page is actually offset from the top so that it's lower than the navbar. The horizontal one is because the vertical one pushes the page to the side

**Comment by Oren-Lindsey** [comment]
I think I fixed it @kccuber-scratch
