### ISSUE TITLE
Recommended UI QOL Changes 7/6/22

### ISSUE THREAD

**Issue by jdev082** [Oren-Lindsey/scratch-cloud#2]
- Show ID of project being viewed in input box
![Group 1(2)](https://user-images.githubusercontent.com/92550746/177601359-fd4c6265-bc25-4578-9454-c24d63b39eb3.png)

**Comment by Oren-Lindsey** [comment]
the problem is the search bar is in the layout, not in the actual page. It would require some hacky stuff to make this work
